### ISSUE TITLE
Error: Google Contact server error.

### ISSUE THREAD

**Issue by Korte68** [riteshvish/google-contacts-crud#4]
It was working for a while, but since a few days i got this:
{ Error: Google Contact server error.
    at Function.GoogleContactsParser.getError (/home/http/mokavar/node_modules/google-contacts-crud/lib/response-parser.js:36:17)
    at /home/http/mokavar/node_modules/google-contacts-crud/lib/google-contacts.js:84:44
    at OAuth2Client._postRequest (/home/http/mokavar/node_modules/google-contacts-crud/node_modules/google-auth-library/lib/auth/oauth2client.js:402:3)
    at postRequestCb (/home/http/mokavar/node_modules/google-contacts-crud/node_modules/google-auth-library/lib/auth/oauth2client.js:362:12)
    at Request._callback (/home/http/mokavar/node_modules/google-contacts-crud/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/home/http/mokavar/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/http/mokavar/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13) code: 400, message: 'Google Contact server error.' }

I did not changed anything...

any idea?

Thank you

**Comment by VM8198** [comment]
@Korte68 
 have you resolved this error ? 
I am also getting this error

**Comment by Korte68** [comment]
Unfortunately not. The developer did not answer at all:(

Az iPhone-omról küldve

2019. ápr. 9. dátummal, 11:40 időpontban VM8198 <notifications@github.com> írta:

**Comment by Garefild** [comment]
Change line 74 in google-contacts.js to "JSON.stringify(options),".
